// All types of Actions in OUR website
export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

// Society Related 
export const FETCH_SOCIETY_DATA = "FETCH_SOCIETY_DATA";
export const LOAD_SOCIETY_DATA = "LOAD_SOCIETY_DATA";
export const FETCH_SOCIETY_ERROR = "LOAD_SOCIETY_ERROR";
export const FETCH_SOCIETY_RETRY = "LOAD_SOCIETY_RETRY";


//MODAL RELATED
export const SHOW_SEARCH_MODAL = "SHOW_SEARCH_MODAL";
export const HIDE_SEARCH_MODAL = "HIDE_SEARCH_MODAL";


export const FETCH_CREATED_EVENT = "FETCH_CREATED_EVENT";
export const LOAD_CREATED_EVENT = "LOAD_CREATED_EVENT";
export const FETCH_CREATED_EVENT_ERROR = "FETCH_CREATED_EVENT_ERROR";
export const FETCH_GUESTANDSPONSOR_DATA = "FETCH_GUESTANDSPONSOR_DATA";
export const LOAD_GUESTANDSPONSOR_DATA = "LOAD_GUESTANDSPONSOR_DATA";
export const FETCH_GUESTANDSPONSOR_DATA_ERROR = "FETCH_GUESTANDSPONSOR_DATA_ERROR";



export const LOAD_ALL_EVENTS = "LOAD_ALL_EVENTS";
export const FETCH_ALL_EVENTS = "FETCH_ALL_EVENTS";
export const FETCH_ALL_EVENTS_ERROR = "FETCH_ALL_EVENTS_ERROR"; 


//User related
export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
export const LOAD_CURRENT_USER = "LOAD_CURRENT_USER";
export const FETCH_CURRENT_USER_ERROR = "FETCH_CURRENT_USER_ERROR" ;
export const FETCH_USER_PERSONAL_DETAILS = "FETCH_USER_PERSONAL_DETAILS";
export const LOAD_USER_PERSONAL_DETAILS = "LOAD_USER_PERSONAL_DETAILS";
export const FETCH_USER_PERSONAL_DETAILS_ERROR = "FETCH_USER_PERSONAL_DETAILS_ERROR";
export const FETCH_CLASS_AND_SCOEITY_DETAILS = "FETCH_CLASS_AND_SCOEITY_DETAILS";
export const LOAD_CLASS_AND_SCOEITY_DETAILS = "LOAD_CLASS_AND_SCOEITY_DETAILS";
export const FETCH_CLASS_AND_SCOEITY_DETAILS_ERROR = "FETCH_CLASS_AND_SCOEITY_DETAILS_ERROR";

// About registered events
export const FETCH_REGISTERED_EVENTS = "FETCH_REGISTERED_EVENTS";
export const LOAD_REGISTERED_EVENTS = "LOAD_REGISTERED_EVENTS";
export const FETCH_REGISTERED_EVENTS_ERROR = "FETCH_REGISTERED_EVENTS_ERROR";

// At time of Event Registration
export const FETCH_REGISTER_EVENT = "FETCH_REGISTER_EVENT"
export const LOAD_REGISTER_EVENT = "LOAD_REGISTER_EVENT";
export const FETCH_REGISTER_EVENT_ERROR = "FETCH_REGISTER_EVENT_ERROR";
