// All types of Actions in OUR website

export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";


//EVENT RELATED WORK
export const LOAD_ALL_EVENTS = "LOAD_ALL_EVENTS";
export const SET_USER_PERSONAL_DETAILS = "SET_USER_PERSONAL_DETAILS";
export const SET_CLASS_AND_SCOEITY_DETAILS = "SET_CLASS_AND_SCOEITY_DETAILS"
export const ADDING_EVENT_DETAILS = "ADDING_EVENT_DETAILS";
